# PHASE 2

### Numpy Array operations

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing \n",arr[2:7])
print("With step \n",arr[2:7:2])
print("Negative indexing \n",arr[-9],arr[0],arr[-1])

Basic slicing 
 [3 4 5 6 7]
With step 
 [3 5 7]
Negative indexing 
 1 1 9


### Indexing on 2D array

In [5]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print("Specific element \n", arr_2d[1,2])  #Means Ist row ka 2nd element
print("Specific element \n", arr_2d[0,0])  #Means zeroth row ka zeroth element
print("Specific element \n", arr_2d[2,2])  #Means 2nd row ka 2nd element
print("Entire Row: \n", arr_2d[1]) 
print("Entire column: \n", arr_2d[:,1]) 

Specific element 
 6
Specific element 
 1
Specific element 
 9
Entire Row: 
 [4 5 6]
Entire column: 
 [2 5 8]


### Sorting

In [7]:
unsorted=np.array([1,2,3,4,5,6,7,8,9])
print("Sorted array",np.sort(unsorted))


unsorted_arr_2d=np.array([[1,2,98],
                 [4,0,6],
                 [7,8,9]])
print("Sorted array",np.sort(unsorted_arr_2d))


print("Entire column: \n", np.sort(unsorted_arr_2d ,axis=0))
print("Entire row: \n", np.sort(unsorted_arr_2d ,axis=1))
print("selected column: \n", np.sort(unsorted_arr_2d[:,1]))
print("selected row: \n", np.sort(unsorted_arr_2d[2]))


Sorted array [1 2 3 4 5 6 7 8 9]
Sorted array [[ 1  2 98]
 [ 0  4  6]
 [ 7  8  9]]
Entire column: 
 [[ 1  0  6]
 [ 4  2  9]
 [ 7  8 98]]
Entire row: 
 [[ 1  2 98]
 [ 0  4  6]
 [ 7  8  9]]
selected column: 
 [0 2 8]
selected row: 
 [7 8 9]


### Filter

In [8]:
numbers=np.array([1,2,3,4,5,6,7,8,9])
even_numbers=numbers[numbers%2==0]
print("Even numbers",even_numbers)

Even numbers [2 4 6 8]


### Fliter with mask

In [9]:
mask = numbers >5
print("Numbers > 5 :", numbers[mask])

mask=numbers%2==0
print("Even numbers :", numbers[mask])

Numbers > 5 : [6 7 8 9]
Even numbers : [2 4 6 8]


### Fancing indexing vs np.where()


In [11]:
indicies =[0,2,4]
print(numbers[indicies])

#np.where --> similar to masking

where_result=np.where(numbers>5)
print("Np where :",numbers[where_result])

[1 3 5]
Np where : [6 7 8 9]


In [12]:
#Array with some conditions

condition_array= np.where(numbers>5)
print(numbers[condition_array])
#lets understand where clause in detail 
condition_array= np.where(numbers>5,numbers*3,numbers*2)
print(condition_array)# this means that if the number is > 5 (in numbers array ) multiply it by 4 else multiply it by 2.

#for better understanding
condition_array= np.where(numbers>5,"true","false")
print(condition_array)



[6 7 8 9]
[ 2  4  6  8 10 18 21 24 27]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


### Add or remove data

In [13]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

combined=arr1+arr2 ##this will add 2 arrays not concatinate
print(combined)

#Now lets concatinate them
combined=np.concatenate((arr1,arr2))
print(combined)



[5 7 9]
[1 2 3 4 5 6]


### Array compatibility

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6,0])
c=np.array([7,8,9])
print("Compatibility Shapesopf a & b :",a.shape==b.shape)
print("Compatibility Shapes of a & c :",a.shape==c.shape)

Compatibility Shapesopf a & b : False
Compatibility Shapes of a & c : True


### some more functions like additing rows or coloumns

In [16]:


orginal=np.array([[1,2],[3,4],])
new_row=np.array([[5,6],[6,1]])#shape should be same 

with_new_row=np.vstack((orginal ,new_row))
print (orginal)

print (with_new_row)
##SHape should be as of orginal array
new_col=np.array([[5,1],[8,6]])
with_new_col=np.hstack((orginal,new_col))
print("\n",with_new_col)



[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]
 [6 1]]

 [[1 2 5 1]
 [3 4 8 6]]


### Deleting from an Array

In [17]:

arr=np.array([[1,2,3,4,5,6,7,8],[23,24,24,4,5,3,9,7]])
deleted=np.delete(arr,12)
print("Array after deletion \n",deleted)

Array after deletion 
 [ 1  2  3  4  5  6  7  8 23 24 24  4  3  9  7]
