PHASE I

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

In [ ]:
### creating array from list

In [16]:
arr_1d=np.array([1,2,3,4,5])
print("1D array; ",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)

1D array;  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


In [17]:
###list vs numpy array

In [20]:
py_list=[1,2,3]
print("pyhton list multipilication: ",py_list*3)
 
np_array=np.array([1,2,3]) #element wise multiplication
print("numoy array multipilication: ",np_array*3)

pyhton list multipilication:  [1, 2, 3, 1, 2, 3, 1, 2, 3]
numoy array multipilication:  [3 6 9]


In [21]:
import time as t 
start=t.time()
py_list=[i*2 for i in range(1000000)]
print("\n list operation time: ",t.time()-start)

start=t.time()
np_array=np.arange(1000000)*2
print("\n Array operation time: ",t.time()-start)
##Numpy is time efficient




 list operation time:  0.07657003402709961

 Array operation time:  0.005298614501953125


In [ ]:
#creating array from scratch

In [22]:
#Crearing zeros array
zeros=np.zeros([3,4])
print("zeros array: \n",zeros)
print("\n")

#Crearing ones array
ones=np.ones([2,3])
print("Ones array: \n",ones)
print("\n")

#creating tuple\array of any constant number
full=np.full((4,3),6)
print("full array: \n",full)
print("\n")




zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


full array: 
 [[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]




In [26]:
##creating matrix with random values
##Here we use np.random.random because random has many methods to use
random=np.random.random([3,4])
print("random array: \n",random)

#np.arange(start, stop, step)
#It expects 3 numbers, not a shape.
#This function returns a 1D array with numbers starting from 0 up to (but not including) 10 with steps of 2.
sequence =np.arange(0,10,2)
print("sequence array \n",sequence)


random array: 
 [[0.89941131 0.27801042 0.37240713 0.3232503 ]
 [0.61926242 0.95436874 0.92145268 0.44367772]
 [0.38099212 0.76669316 0.86391138 0.34150188]]
sequence array 
 [0 2 4 6 8]


In [27]:
#vector , matrix and tensor
vector=np.array([1,2,3])
print("Vector \n",vector)

Vector 
 [1 2 3]


In [28]:
matrix=np.array([[1,2,3],
                 [4,5,6]])
print("matrix\n",matrix)

matrix
 [[1 2 3]
 [4 5 6]]


In [29]:
tensor=np.array([[1,2,3],
                 [4,5,6],
                 [5,6,7,]])
print("tensor\n",tensor)

tensor
 [[1 2 3]
 [4 5 6]
 [5 6 7]]


#Array properties

In [30]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("shape \n",arr.shape)
print("dimension \n",arr.ndim)
print("size \n",arr.size)
print("datatype \n",arr.dtype)

shape 
 (2, 3)
dimension 
 2
size 
 6
datatype 
 int64


Array reshapping

In [31]:
arr=np.arange(12)
print("original array \n",arr)

reshaped=arr.reshape((3,4))
print("reshaped array \n",reshaped)

flattened=reshaped.flatten()
print("flattended array \n",flattened)

##ravel (returns view, instead of copy i.e flatten returns copy)
raveled=reshaped.ravel()
print("\n ravled array" ,raveled)

#Transpose

transpose=reshaped.transpose()
print("Transpose  \n", transpose)


original array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattended array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 ravled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose  
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
